env:
  DEBIAN_FRONTEND: noninteractive
  rsa_git: "ENCRYPTED[497d561ab5e2e382a4c76a449f0e474cb516e451542167e9bb4fc61f2cbaac422cee9f48f29fe60ffd7d8ff6e4646184]"
  rsa_sf: "ENCRYPTED[7b295a292ba10acd5a3f041b301fe03e96a18bfff4782789673fd2a8fca48a4c68aa9203a56645bf14a91fc1ed068ddb]"
  packages: "bash coreutils curl clang git make tar sudo ssh"
  username: "Hacker IITK (aryan)"
  useremail: "aryaniitk2021@gmail.com"

task:
  name: Buildup LineageOS
  timeout_in: 2h
  container:
    image: ubuntu:20.04
    cpu: 8
    memory: 24GB

  Setup_script:
    - apt update &>/dev/null;echo -e "\n\n-----        Installing Packages       ------\n\n";time apt install $packages -y &>/dev/null;cd /usr/local/bin && bash -c "$(curl -L git.io/file-transfer)";cd - || exit
    - lz4_install() { git clone https://github.com/lz4/lz4 --depth=1;cd lz4;PREFIX=/usr;make install;}
    - lz4_install
    - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
    - git config --global user.name "$username";git config --global user.email "$useremail";git config --global color.ui true
    - mkdir ~/.ssh &>/dev/null || true;echo "$rsa_git" > ~/.ssh/id_rsa;echo "$rsa_sf" > ~/.ssh/id_sf && chmod 600 ~/.ssh/id_*
    - echo -e "\n\nTesting ssh key" && ssh -T git@github.com -o 'StrictHostKeyChecking no' || true
    - echo -e "\n\n\n\n------      Setting Up Build Environment     ------\n\n\n\n"
    - time bash -c "$(curl -L https://raw.githubusercontent.com/aryankaran/build-env-setup/main/envsetup.sh  2>/dev/null)" &>/dev/null
    - echo -e "\n\n----   Adding user aryan ----\n\n"
    - adduser --gecos "" --disabled-password aryan;passwd -d aryan;usermod -aG sudo aryan;cp ~/.gitconfig /home/aryan;cp ~/.ssh /home/aryan -R;chown -R aryan:aryan /home/aryan/.gitconfig /home/aryan/.ssh
    - echo -e "\n\n\n\n\n\n\n\n----   Time to do some source code download  ---\n\n\n\n\n\n\n\n"
    - runuser -l aryan -c "echo -e '\n\nTesting ssh key' && ssh -T git@github.com -o 'StrictHostKeyChecking no' || true"
    - runuser -l aryan -c "df -h . && mkdir lineage;cd lineage;repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --depth=1 && git clone https://github.com/aryankaran/local_manifests -b LineageOS --depth=1 .repo/local_manifests && time repo sync -c -j8 --force-sync --no-clone-bundle --no-tags || time repo sync -c -j8 --force-sync --no-clone-bundle --no-tags || repo sync -j1 || repo sync"
    - echo -e "\n\n\n\n\n\n\n\n------      Doing actual Build     --------\n\n\n\n\n\n\n\n"
    - runuser -l aryan -c "timeout 8m bash -c 'cd ~/lineage;source build/envsetup.sh || . build/envsetup.sh || true && export USE_CCACHE=1 && export CCACHE_DIR=/home/aryan/ccache && export OUT_DIR=/home/aryan/out && ccache -s && export KBUILD_BUILD_USER=aryan && export KBUILD_BUILD_HOST=AryanLappyHP && brunch onclite' || true"

  Push_script:
    - cd /home/aryan && time tar --use-compress-program=lz4 -cf "ccache-$(date | sed 's-:-.-g').tlz4" ccache& time tar --use-compress-program=lz4 -cf "out-$(date | sed 's-:-.-g').tlz4" out && transfer wet *lz4 || true ls -lhA
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_sf *tlz4 aryankaran@frs.sf.net:/home/users/a/ar/aryankaran/builds

  Post_script:
    - cd $CIRRUS_WORKING_DIR && echo "$(date)" > files && git add files && git commit -m "$(date)" && git remote add me git@$CIRRUS_REPO_CLONE_HOST:$CIRRUS_REPO_FULL_NAME && git push me
    
